name: sp-web3

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - supabase
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - supabase
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  supabase:
    external: true
    name: supabase_network_sp-web3
